import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import AppHeader from "@/components/AppHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ArrowLeft, Music, Image, FileText, DollarSign, Sparkles, Copy, Check, X, FileStack, Loader2, Wand2, Download, Upload, ImageIcon, FolderOpen, RefreshCw, Volume2, Square, Mic, Trophy, TrendingUp, ExternalLink, Zap, Rocket } from "lucide-react";
import ElevenLabsIcon from "@/components/icons/ElevenLabsIcon";
import { useToast } from "@/hooks/use-toast";
import type { User } from "@supabase/supabase-js";
import ImageSourcePicker from "@/components/ImageSourcePicker";
import PaidAdsDashboard from "@/components/PaidAdsDashboard";
import { useClientContext } from "@/contexts/ClientContext";
import linkedinLogo from "@/assets/linkedin-logo.png";
import snapchatLogo from "@/assets/snapchat-logo.png";
